cocofarm-prs:
        image: registry.navercorp.com/cocofarm/cocofarm-prs:${TAG}
        labels:
                - "COCOFARM_SERVICE_TAG=${TAG}"
                - "COCOFARM_SERVICE_NAME=cocofarm-prs"
                - "COCOFARM_SERVICE_SSUID=cocofarm"
                - "COCOFARM_SERVICE_ROLE=prs"
                - "COCOFARM_SERVICE_TAGS=link=/search.naver,environment=standby,ssuid=cocofarm,role=prs,tag=${TAG}"
                - "COCOFARM_SERVICE_CHECK_HTTP=/monitor/l7check.html"
        ports:
                - "20000"
        environment:
                - CLUSTER_TYPE=devel
        # cpu : 2 core
        cpu_limit: 2
        # memory : 4G
        mem_limit: 4000000000
