---
filebeat.prospectors:

################################################################################
# 
# 코코팜 컨테이너 사용자를 위한 filebeat 설정파일 탬플릿입니다.
# (dl_logiss@navercorp.com)
#
# TODO를 찾아서 수정하면 컨테이너 시작시 filebeat 가 실행됩니다.
#

################################################################################
#
# httpd access 로그 설정
# logiss-prs의 pc.logiss 라는 로그를 로기스로 전송하는 설정입니다.
#
- input_type: log
  paths:
    # TODO httpd.conf에서 로그가 아래 경로, 이름에 쌓이는 지 확인합니다.
    - /naver/${SERVICE}/var/log/pc.access

  tail_files: true
  fields_under_root: true
  fields:
    ssuid: "${SSUID}"
    # TODO 쿼리소스가 nx이라면 아래의 pc를 nx으로 수정합니다.
    cid: "pc,${HOSTNAME:?Set the HOSTNAME env variable}"
    role: "${ROLE}"
    format: "accesslog1"

################################################################################
#
# httpd access 로그 설정
# logiss-prs의 mobile.logiss 라는 로그를 로기스로 전송하는 설정입니다.
#
- input_type: log
  paths:
    - /naver/${SERVICE}/var/log/mobile.access

  tail_files: true
  fields_under_root: true
  fields:
    ssuid: "${SSUID}"
    # TODO 쿼리소스가 m이라면 아래의 mobile을 m으로 수정합니다.
    cid: "mobile,${HOSTNAME:?Set the HOSTNAME env variable}"
    role: "${ROLE}"
    format: "accesslog1"

################################################################################
#
# httpd access 로그 설정
# logiss-prs의 tab.logiss 라는 로그를 로기스로 전송하는 설정입니다.
#
- input_type: log
  paths:
    - /naver/${SERVICE}/var/log/tab.access

  tail_files: true
  fields_under_root: true
  fields:
    ssuid: "${SSUID}"
    # TODO 쿼리소스가 svc이라면 아래의 tab을 svc로 수정합니다.
    cid: "tab,${HOSTNAME:?Set the HOSTNAME env variable}"
    role: "${ROLE}"
    format: "accesslog1"

#
# TIP: access가 더 있다면 위의 세 개 중 하나를 복사해서 만들면 됩니다.
#

################################################################################
#
# error 로그 설정 예
# (에러 로그 전송이 필요없으면 아래 12줄을 모두 주석처리 합니다.)
#

- input_type: log
  paths:
    - /naver/${SERVICE}/var/log/error
  fields_under_root: true
  fields:
    ssuid: "${SSUID}"
    cid: "${HOSTNAME:?Set the HOSTNAME env variable}"
    role: "${ROLE}_error"

    # format에는 errorlog1으로 기록하며, 로기스에서 지정한 아래 타임 포맷으로
    # 시작하는 에러 로그가 수집됩니다.
    #
    # [E MMM dd HH:mm:ss yyyy]    e.g. [Wed Jul 05 10:27:08 2017]
    # [yyyy-MM-dd HH:mm:ss.SSS]   e.g. [2017-07-06 00:00:00.526]
    #
    format: "errorlog1"
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after

################################################################################
#
# filebeat 설정
#
# 로그 전송 중에 만들어질 임시파일 저장 경로입니다. 로그는 거의 남지 않고,
# 데이터도 수백 바이트만 쓰니 안심하시고 경로를 확인해주세요.

# TODO 다른 경로에 쌓이길 원한다면 수정합니다.
path.data: /naver/${SERVICE}/var/logiss_data

# TODO 다른 경로에 쌓이길 원한다면 수정합니다.
path.logs: /naver/${SERVICE}/var/log

################################################################################
#
# filebeat 설정 (수정하지 마세요)
#

logging.level: critical
logging.to_files: true
logging.to_syslog: false
logging.files:
  name: logiss_filebeats.log
  keepfiles: 7

output.logstash:
  hosts: ${LOGISS_HOSTS} # logiss front-end
  loadbalance: true

...
# vim: sw=2 ts=2 et
