[[snippets]]
  description = "parallel default"
  command = "parallel \"ssh irteamsu@{} 'echo {};'\" ::: css1210 css1298 css(seq -w 0553 0555)"
  output = ""

[[snippets]]
  description = "tshark over ssh"
  command = "ssh irteamsu@cccf001 \"sudo /usr/sbin/tcpdump -i any -U -w - port not 22\" | tshark -i -"
  output = ""

[[snippets]]
  description = "curl swarm default"
  command = "curl -G -XGET --cacert /naver/cocofarm/etc/key/ca.pem --key /naver/cocofarm/etc/key/key.pem /naver/cocofarm/etc/key/cert.pem https://csb70795.nfra.io:2376/service/json"
  output = ""

[[snippets]]
  description = "curl docker filter"
  command = "curl -G -XGET --cacert /naver/cocofarm/etc/key/ca.pem --key /naver/cocofarm/etc/key/key.pem /naver/cocofarm/etc/key/cert.pem https://csb70795.nfra.io:2376/service/json -d 'all=1' --data-urlencode 'filters={\"label\":[\"com.docker.swarm.hidden=true\"]}'"
  output = ""

[[snippets]]
  description = "jq default"
  command = "jq -r '.services[][] | .ServiceName + \" \" + .Address + \":\" + (.ServicePort|tostring)'"
  output = ""

[[snippets]]
  description = "sort default"
  command = "sort -u -k 1,1"
  output = ""

[[snippets]]
  description = "tr default"
  command = "tr \" \" \"\\n\""
  output = ""

[[snippets]]
  description = "docker container pid"
  command = "docker inspect --format '{{.State.Pid}}' NAME"
  output = ""

[[snippets]]
  description = "kerberos keytab creating"
  command = "set user <user>; set pass <password>; printf \"%b\" \"addent -password -p $user -k 1 -e des-cbc-crc\\n$pass\\nwrite_kt $user.keytab\" | ktutil"
  output = ""

[[snippets]]
  description = "kerberos login"
  command = "kinit -k -t <keytabfilepath> <username> -l 24hrs"
  output = ""

[[snippets]]
  description = "socat default"
  command = "socat tcp-listen:2222,reuseaddr tcp:localhost:22"
  output = ""

[[snippets]]
  description = "tcpdump default"
  command = "tcpdump -np port 2222 and not port 42928"
  output = ""

[[snippets]]
  description = "openssl x509 default"
  command = "openssl x509 -in manager.crt  -text"
  output = ""

[[snippets]]
  description = "du default"
  command = "du -chs /*"
  output = ""

[[snippets]]
  description = "find default"
  command = "find . -maxdepth 5 -not -name \"*.txt\" -name '*.sample' -type f -size +0M -exec stat '{}' \\;"
  output = ""

[[snippets]]
  description = "rsync default"
  command = "rsync -av SOURCE TARGET --bwlimit=10000"
  output = ""

[[snippets]]
  description = "git log default"
  command = "git log -p -1"
  output = ""

[[snippets]]
  description = "git log search"
  command = "git log -S"
  output = ""

[[snippets]]
  description = "git check merged branches"
  command = "git branch --merged"
  output = ""

[[snippets]]
  description = "git delete remote branch"
  command = "git push origin --delete"
  output = ""

[[snippets]]
  description = "git delete remote tag"
  command = "git push <remote=origin> :refs/tags/<tag>"
  output = ""

[[snippets]]
  description = "ps cpu top 10"
  command = "ps -eo pcpu,pid,ppid,user,args | sort -k1 -r | head -10"
  output = ""

[[snippets]]
  description = "strace default"
  command = "strace -f -e trace=mount -s 1024 -v -p ${PID}"
  output = ""

[[snippets]]
  description = "git log commit"
  command = "git --no-pager log --pretty=format:\"%h\" $FILE"
  output = ""

[[snippets]]
  description = "git show default"
  command = "git show $COMMIT:$FILE"
  output = ""

[[snippets]]
  description = "awk default"
  command = "awk -F: '/^[^#]/{print $1}'"
  output = ""

[[snippets]]
  description = "awk start with"
  command = "awk -F: '$1 ~ /^1/'"
  output = ""

[[snippets]]
  description = "curl unix hex"
  command = "curl -s --unix /var/run/docker.sock 'http://localhost/containers/cocostats-agent/logs?timestamps=1&stdout=1&tail=1&follow=0' --output - | hexdump -C | head"
  output = ""

[[snippets]]
  description = "jq with less"
  command = "cat test.json | jq -C . | less -r"
  output = ""

[[snippets]]
  description = "git find branch which has the COMMIT"
  command = "git branch --all --contains COMMIT"
  output = ""

[[snippets]]
  description = "awk get diff with previous line"
  command = "awk '{print $16}' | awk 'NR == 1 {old=$1; next}{print $1 - old; old = $1}'"
  output = ""

[[snippets]]
  description = "jq with consul service filtering"
  command = "jq -c '.[] | select(.Service|contains(\"test1-keyolk\"))'"
  output = ""

[[snippets]]
  description = "tail with timestamp"
  command = "tail -f crontabui-stdout.log | awk '{now=strftime(\"%F %T%z\\t\");sub(/^/, now);print}'"
  output = ""

[[snippets]]
  description = "sed with regex group capture"
  command = "sed -r 'N;N;s/(.*)\\n.*CPU: (.*) Mem: (.*).*\\/.*\\n.*CPU: (.*) Mem: (.*).*\\/.*/\\1\\t|\\t\\2 \\3\\t\\t|\\t\\4 \\5/g'"
  output = ""

[[snippets]]
  description = "dump http header from 21481 port"
  command = "tcpdump -A -s 10240 'tcp port 21481 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)' | egrep --line-buffered \"^........(GET |HTTP\\/|POST |HEAD )|^[A-Za-z0-9-]+: \" | sed -r 's/^........(GET |HTTP\\/|POST |HEAD )/\\n\\1/g'"
  output = ""

[[snippets]]
  description = "xpane to all docker node"
  command = "xpanes -c \"ssh <account=irteam>@{}\" (docker node ls --format '{{.Hostname}}')"
  output = ""

[[snippets]]
  description = "xpane to all docker manager"
  command = "xpanes -c \"ssh <account=irteam>@{}\" (docker node ls --filter role=manager --format '{{.Hostname}}')"
  output = ""

[[snippets]]
  description = "xpane to all docker worker"
  command = "xpanes -c \"ssh <account=irteam>@{}\" (docker node ls --filter role=worker --format '{{.Hostname}}')"
  output = ""

[[snippets]]
  description = "make stat using awk and sort, uniq"
  command = "zcat access.gz  | awk '{split($8, a, \"/\"); print substr($5,14,2), a[2]}' | sort | uniq -c"
  output = ""

[[snippets]]
  description = "tcpdump HTTP GET"
  command = "tcpdump -nn -A -X -i any -c 100 -s 1500 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420'"
  output = ""

[[snippets]]
  description = "tcpdump HTTP POST"
  command = "tcpdump -nn -A -X -i any -c 100 -s 1500 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354'"
  output = ""

[[snippets]]
  description = "tcpdump HTTP request/response"
  command = "tcpdump -nn -A -X -i any -c 100 -s 1500 '((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0'"
  output = ""

[[snippets]]
  description = "lsof"
  command = "lsof -i -a -p ${PID}"
  output = ""

[[snippets]]
  description = "openssl check modulus of private key"
  command = "openssl rsa -modulus -noout -in <privkey> | openssl md5"
  output = ""

[[snippets]]
  description = "openssl check modulus of public key"
  command = "openssl x509 -modulus -noout -in <publickey> | openssl md5"
  output = ""

[[snippets]]
  description = "tcpdump http req/resp"
  command = "tcpdump -A -s 0 'tcp port 80 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)'"
  output = ""
